### ISSUE TITLE
SQL Developer Extension Development

### ISSUE THREAD

**Issue by joelferreira** [scristalli/SQL-Developer-4-keepalive#10]
Hi,

I'm new to the development of extensions for SQL Developer. While I was reading about it, I found you extension, and it has some things that are like what I want to develop, so I was trying to use your code for some tests. I was able to install the extension, using your .zip file. However, when i tried to change something (like the dialog message when you click in the icon) and create a similar .zip file I was not able to install the extension in SQL developer. 

Can you give me a little help with this? I'm using JDeveloper 12c (12.1.2.0.0) and trying to install the extension in SQL Developer 4 (4.0.3.16).

Sorry to write it here, but it was the only way that I found to contact you.

Thanks in advance,
Best regards

**Comment by scristalli** [comment]
It is a good idea to make a tutorial for modifying and recompiling the extension, in fact the major challenge while developing the extension has been finding the documentation and making the examples work.
I plan to make such a guide, but at the moment I don't have time for this project. A realistic date for me to complete this would be September 2015. I would give you quick advice if I could, but I made the extension months ago and I don't have enough information to help you at the moment.
If someone managed to recompile the extension, as usual the wiki can be edited.

Best regards.

**Comment by scristalli** [comment]
"How to build" is now available in the Wiki! :)
Please provide feedback if you want.
