### ISSUE TITLE
SQL Developer 4.0.3 - icon dissapears after restart

### ISSUE THREAD

**Issue by rawson2** [scristalli/SQL-Developer-4-keepalive#11]
I managed to install the extension succesfully. Unfortunately, after next restart of SQL Developer the icon dissapeared. The application doesn't show the installed extension in Tools -> Features... -> Installed Updates.
I checked if the files went missing, but they are all in their place in the folders of sqldeveloper application.
I tried to install keepalive again and the icon appears right after the installation, but another restart of SQL Developer brings the issue again.

**Comment by scristalli** [comment]
Plase specify the following details regarding your installation:
- operating system
- keepalive version

**Comment by scristalli** [comment]
I'm unable to reproduce the bug on Ubuntu Linux 14.10, SQL Developer 4.0.3, keepalive 1.3

**Comment by scristalli** [comment]
I'm closing the issue as "cannot reproduce" for now, if you can provide more detail we might re-open.
