### ISSUE TITLE
SQLDeveloper 4.1.1 Keepalive Icon Missing from Toolbar

### ISSUE THREAD

**Issue by wblumstengel** [scristalli/SQL-Developer-4-keepalive#12]
Just upgraded to SQLDeveloper 4.1.1 and reinstalled Keepalive.  However, the Keepalive icon does not appear on the toolbar after installation.

**Comment by aullik** [comment]
Same here. SQL Dev doesnt seem to upgrade. I cannot find it in 'Features and Updates'.

**Comment by jdiazest** [comment]
Hello, I have just upgraded from SQLDeveloper 4.0.3 to 4.1.0 and keepalive icon disappeared.

I manually deleted old files of keepalive instalation and then reinstalled Keepalive and it already works ok.

**Comment by scristalli** [comment]
If we can have feedback from at least another user having this problem and @jdiazest solution works, I think we can mark this as resolved and include the workaround in the Wiki.

**Comment by wblumstengel** [comment]
Hi

I am running v4.1.1 build 1959.  I think the solution is not so much removing old files associated with keepalive, but instead launching SQLDeveloper with admin privileges (i.e. starting SQLDeveloper by right-clicking on the program icon (or shortcut) and selecting "run as administrator").  Once I started SQLDeveloper with admin privileges, I could install keepalive, and the keepalive toolbar icon would be present after restarting SQLDeveloper.

C:\Users\<username>\AppData\Roaming\SQL Developer\system4.1.1.19.59

**Comment by RichardSoule** [comment]
To follow up on wblumstengel's comments, it's definitely a permissions issue. On Linux (installed sqldeveloper as root, using it as oracle/others) you have to go through a whole bunch of machinations settings the permissions/ownership of various files/directories to get things to work. Using command line to start sqldeveloper helped me track everything down. I had to restart it a few times, but each time I did the console would tell me which file/directory needed to be writeable/readable by the current user.

**Comment by scristalli** [comment]
I'm closing this, as it appears the problem has been identified (and a solution has been provided).
@RichardSoule if you have different commands from the brutal ```chmod 666``` that I reported in the wiki, feel free to edit the wiki directly,
