### ISSUE TITLE
Won't install on 4.1.5.21

### ISSUE THREAD

**Issue by lamikam** [scristalli/SQL-Developer-4-keepalive#22]
Followed steps - Zip does not contain a bundle manifest in META-INF/bundle.xml

**Comment by dademiller** [comment]
same problem, did you solve it? thx

**Comment by guillermoml** [comment]
Just in case anybody have this problem: you must download the plugin from the [Releases](https://github.com/scristalli/SQL-Developer-4-keepalive/releases) page.
The zip generated from the _Clone or Download_ button causes this message.

**Comment by scristalli** [comment]
Not an issue of the extension (related to downloading wrong ZIP file).
