### ISSUE TITLE
SQL developer freeze after extension install

### ISSUE THREAD

**Issue by mastro83** [scristalli/SQL-Developer-4-keepalive#26]
Hi to all, how clean uninstall keepalive extension? It cause problems. Thanks.

**Comment by scristalli** [comment]
Resolved, I assume?

**Comment by mastro83** [comment]
I found where uninstall the extension but when I attempt to close sqldeveloper it remains in backgroup for 5-10 minutes inhibiting me to shut down the macbookpro. high sierra.

**Comment by scristalli** [comment]
This looks to me like the _n_-th bug of SQL Developer due to its inability to correctly handle extensions.
Can you reproduce the bug every time you close SQL Developer? Could you try reinstalling and see if anything changes?

**Comment by mastro83** [comment]
E' l'ennesimo bug di SQL Developer. Risolto reinstallandolo.
