### ISSUE TITLE
Running the extension automatically at startup

### ISSUE THREAD

**Issue by kilx** [scristalli/SQL-Developer-4-keepalive#8]
Please add option for the extension to start automatically. Or remember the previous state after SQL Developer restart.

**Comment by scristalli** [comment]
This is a good suggestion, however currently I'm not able to put time into the development of this extension, even for a small change. I'll probably have some time in March, in the meantime if someone wants to take care of this I'll be happy to merge. Just please keep changes to a minimum for the same reason (less time to verify before merging).

**Comment by scristalli** [comment]
It seems that this might be harder than I thought, considering that OSGi performs lazy loading of extensions and there is no trigger for startup.

I will not try to develop this feature, but I will leave this issue open in case someone comes up with an idea.

**Comment by scristalli** [comment]
I have been able to do some additional research on this. Not only this seems to be forbidden by design, but also I was not able to find a hack around the issue.

This feature will **not** be developed.
